development:
  adapter: sqlite3
  database: db/db.db

# test:
# adapter:
# database:

production:
  adapter: postgresql
  database: speakermonitor
  username: vmarsterson
  password: password
  host: ENV["DATABASE_URL"]