@startuml activity
    Setup --> Database_setup : create db with speaker and team_member tables
    Database_setup --> Seed : createa and insert seed data into databases
    Seed --> Front_end : design basic front end with CRUD features
    Front_end --> Styling : style front end
    Styling --> Heroku : deploy on Heoku
@enduml