@startuml user_path
    start   
    repeat 
        :enter landing page;
    if (click on speaker image?) then (yes)
        : show bio with jqery;
       : click away from bio;
    else (no)
    :click on 'more info'?;
    :redirect to new page;
    end
@enduml